### ISSUE TITLE
pageControl 分页的小点

### ISSUE THREAD

**Issue by Cyynet** [LvJianfeng/LLCycleScrollView#1]
当用手不断滑动时，下面的分页小圆点没有跟着图片对应  总体体验很好，希望这个库越来越好

**Comment by LvJianfeng** [comment]
@Cyynet  😄 嗯嗯 ，感谢支持。

**Comment by LvJianfeng** [comment]
@Cyynet  请使用1.2.5版本，感谢支持。

**Comment by Cyynet** [comment]
好的，感谢


发自网易邮箱大师
在2017年02月18日 13:24，Crazyf 写道：

@Cyynet 请使用1.2.5版本，感谢支持。
