### ISSUE TITLE
Failed to update auto layout status

### ISSUE THREAD

**Issue by brandy2015** [LvJianfeng/LLCycleScrollView#10]
Hi,

Issues still remained.My Xcode is 8.3.3
It's same to #8 #9 
file:///xcode/%E6%88%91%E5%9C%A8%E9%87%8D%E5%86%99/xxxx/Main.storyboard: error: IB Designables: Failed to update auto layout status: dlopen(LLCycleScrollView.framework, 1): Library not loaded: .framework/Kingfisher
Referenced from: LLCycleScrollView.framework
Reason: image not found

I pod update the podfile. Then restart my Xcode. Problem still lay there.

**Comment by LvJianfeng** [comment]
@brandy2015  Hi,  i think this is cocoapod problem, you can see https://stackoverflow.com/questions/30053144/dyld-library-not-loaded-with-cocoapods-0-37-and-xcode-6-3/30166310#30166310 
or 
https://github.com/CocoaPods/CocoaPods/issues/3586
If you are worried, you can delete @IBDesignable and i will delete it later.

**Comment by brandy2015** [comment]
Yes,I just want to say I delete the @IBdesignable. If I see your feedback, I could have saved a lot of  time. Thank you for your help. Your work is great. Best wishes^_^. Keep in touch.

**Comment by LvJianfeng** [comment]
@brandy2015  haha, Thank you for support. You can update to 1.3.2, I just updated to avoid other people experiencing the same problem. I'll update it later.


The 1.3.1 version and before also contains ibdesignable. 😄
