### ISSUE TITLE
imagesURLStrings

### ISSUE THREAD

**Issue by shenmiaoling** [LvJianfeng/LLCycleScrollView#12]
本地图可以显示，网络图显示不了

**Comment by LvJianfeng** [comment]
这个已经应用了很多项目了呢，有问题还请详细描述。

**Comment by shenmiaoling** [comment]
找到原因了，原来是我的项目没有把 info.plist 的 Allow Arbitrary Loads 设为 YES，这样才能加载 http 路径的图片
