### ISSUE TITLE
更新到Swift4了

### ISSUE THREAD

**Issue by shen5214444887** [LvJianfeng/LLCycleScrollView#13]
你没适配Swift4啊，你引用的Kingfisher不能自动更新到Swift4，能速度更新一下吗，今天刚更新的

**Comment by zanyzephyr** [comment]
![image](https://user-images.githubusercontent.com/23650458/30688985-3d741bbc-9e85-11e7-8e9b-f39251f1d12a.png)
为什么pods库里没有找到1.3.5呢？已经使用<code>pod repo update</code>更新过了呀🤔

**Comment by LvJianfeng** [comment]
不好意思，push trunk 发生了 xcodebuild 问题，你们如果急用的话，建议先使用LLCycleScrollView里的源文件吧

**Comment by zanyzephyr** [comment]
@LvJianfeng 没事儿，同学辛苦了😄

**Comment by LvJianfeng** [comment]
@shen5214444887 @zanyzephyr   好了啦，可以在试试了。

**Comment by zanyzephyr** [comment]
@LvJianfeng 好的，已经更新了
