### ISSUE TITLE
怎么支持xib？

### ISSUE THREAD

**Issue by wonin5** [LvJianfeng/LLCycleScrollView#14]
我使用xib出现如图情况，Swift4.0
![6efe6127cee0e9d5f5fbb4b45a5bba23](https://user-images.githubusercontent.com/11567103/30903211-8f64995e-a3a0-11e7-8ea1-dfc1adb0c0af.jpg)

**Comment by LvJianfeng** [comment]
IB属性已经取消了，所以你要手动给数据呢。

发自我的 iPhone

**Comment by wonin5** [comment]
你好，xib怎么毁回调点击事件呢？

**Comment by LvJianfeng** [comment]
看demo哦，里面有代码。
