### ISSUE TITLE
没有1.4x版本

### ISSUE THREAD

**Issue by dongshangtong** [LvJianfeng/LLCycleScrollView#17]
pod 什么还没有没有见1.4x 版本。我刚好用swift4.0写

**Comment by LvJianfeng** [comment]
有的呢，https://cocoapods.org/pods/LLCycleScrollView
如果不行可以 pod setup 在试试。

**Comment by dongshangtong** [comment]
可以了！果然有了！非常谢谢你！

发自我的 iPhone

**Comment by LvJianfeng** [comment]
@dongshangtong  不客气。
