### ISSUE TITLE
自定义pageControl的位置

### ISSUE THREAD

**Issue by X-my** [LvJianfeng/LLCycleScrollView#2]
我希望能自定义pageControl的位置，最好能设置居左居中居右，或者把pageControl这个属性公开出来，我可以在layout里自己控制位置，希望能尽快支持，眼下我只能自己再加一个pageControl了

**Comment by LvJianfeng** [comment]
嗯，可以的，明天我看下啊

发自我的 iPhone

**Comment by X-my** [comment]
感谢这么快更新，试了一下，居左和居右的枚举设置之后，出来的效果是反的，比如设置为.right后，pagecontrol实际在左边

**Comment by LvJianfeng** [comment]
@X-my  嗯嗯，感谢。有时间我改下，最近忙。
