### ISSUE TITLE
这里要判断nil，不然传入参数为nil，会报错

### ISSUE THREAD

**Issue by zjw7sky** [LvJianfeng/LLCycleScrollView#22]
![image](https://user-images.githubusercontent.com/8446716/32876961-c9d6af42-ca64-11e7-86d9-c01c1397362b.png)

**Comment by LvJianfeng** [comment]
@zjw7sky 
不会的哦，不用给数据的
默认是```titles:Array<String>? = []```

**Comment by zjw7sky** [comment]
这个是默认值，如果我外部传入nil，就崩溃了

**Comment by LvJianfeng** [comment]
@zjw7sky  嗯嗯，我加固一下。

**Comment by LvJianfeng** [comment]
@zjw7sky  
```
 🚀  LLCycleScrollView (1.4.2) successfully published
```
