### ISSUE TITLE
这种情况下，会出现一个灰色背景，不太合理

### ISSUE THREAD

**Issue by zjw7sky** [LvJianfeng/LLCycleScrollView#23]
![image](https://user-images.githubusercontent.com/8446716/32926233-28a3a0d0-cb81-11e7-87b6-4bbd0ca8899b.png)
![image](https://user-images.githubusercontent.com/8446716/32926250-43e92356-cb81-11e7-9602-e554246fe31e.png)

**Comment by LvJianfeng** [comment]
灰色？占位图吧，你可以把占位图改了。

发自我的 iPhone

**Comment by zjw7sky** [comment]
我把他颜色改为透明，但是cell那里直接设置hidden，有点太强硬了

**Comment by LvJianfeng** [comment]
不用，创建的时候给它hidden了就可以了，颜色的控制是方便使用的呢。
```
LLCycleScrollView (1.4.3) successfully published
```
