### ISSUE TITLE
1、不能设置图片为nil；2、数据为空的时候的不能设置图片的显示mode

### ISSUE THREAD

**Issue by zjw7sky** [LvJianfeng/LLCycleScrollView#24]
![image](https://user-images.githubusercontent.com/8446716/33112305-813c6c12-cf8d-11e7-8d3f-72679b98b455.png)
![image](https://user-images.githubusercontent.com/8446716/33112322-9e310440-cf8d-11e7-9ddc-f8a58aadb02d.png)

**Comment by LvJianfeng** [comment]
@zjw7sky 你好，1：图片不会为空的，coveImage存在才会进行coverViewImage的重新赋值。2：我修复一下，如果急用，可以在获取到数据后进行mode的赋值。

**Comment by zjw7sky** [comment]
1、有些设计是，不留默认图，直接空白
2、mode应该在2种情况下都可以设置好点

**Comment by LvJianfeng** [comment]
@zjw7sky   
1，空白的话，可以给coverViewImage赋个透明图或者白图就可以的了。

**Comment by LvJianfeng** [comment]
@zjw7sky  新版本1.4.4，感谢指正。
