### ISSUE TITLE
autoScroll 不能在这里设置为ture

### ISSUE THREAD

**Issue by zjw7sky** [LvJianfeng/LLCycleScrollView#25]
![image](https://user-images.githubusercontent.com/8446716/33193012-7f4b0854-d100-11e7-8aa9-9b0edaefafec.png)

**Comment by LvJianfeng** [comment]
@zjw7sky  你说的是infiniteLoop冲突问题？

**Comment by zjw7sky** [comment]
在这里设置 如果有图片，就一定会自动切换，失去了这个属性的意义
