### ISSUE TITLE
点击事件处理的不是很好。

### ISSUE THREAD

**Issue by CymPlus** [LvJianfeng/LLCycleScrollView#29]
能单独处理下点击事件吗

**Comment by LvJianfeng** [comment]
现在点击回调有两种方式
1.初始化实现
2.声明控件变量，在需要的地方实现控件闭包

你说的单独处理是想要代理吧。这个我后面加上去啊，现在的话，如果你回调里代码量大的话，要么单独实现闭包，要么单独写个函数呢，这几天没有去迭代它呢，后面会如期迭代，感谢。

**Comment by LvJianfeng** [comment]
@CymPlus  
已更新1.4.6

增加协议
