### ISSUE TITLE
Remainder of division by zero

### ISSUE THREAD

**Issue by LinXunFeng** [LvJianfeng/LLCycleScrollView#30]
你好，在这个方法中，当imagePaths为0的时候需要先判断再计算，不然就崩溃了
func pageControlIndexWithCurrentCellIndex(index: NSInteger) -> (Int) {
    return Int(index % imagePaths.count)
}

**Comment by LvJianfeng** [comment]
@LinXunFeng  嗯，可以加点保障。不过理论上是不会在这边出问题的。感谢。
