### ISSUE TITLE
纯文本放在tableView的header的时候, 文本整体高度固定, 字体没有居中

### ISSUE THREAD

**Issue by JoshuaFeng5** [LvJianfeng/LLCycleScrollView#31]

**Comment by LvJianfeng** [comment]
@JoshuaFeng5  你好，由于年前比较忙哈，我看了下木有你说的问题呀，还请详细点

**Comment by JoshuaFeng5** [comment]
当高度很小的时候, 布局就乱了...., 相同的情况下sdcycle就没事, 我换了........

**Comment by LvJianfeng** [comment]
@JoshuaFeng5  好的，我在设置高度为20没有发生你说的问题。
还是感谢支持哈，加油。
