### ISSUE TITLE
snake style 下设置pageControl的FillPageControlIndicatorRadius有问题 选中点不变化

### ISSUE THREAD

**Issue by wish-pig** [LvJianfeng/LLCycleScrollView#32]
// Demo--延时加载数据之滚动方向控制
        let bannerDemo1 = LLCycleScrollView.llCycleScrollViewWithFrame(CGRect.init(x: 0, y: bannerDemo.ll_y + 205, width: w, height: 200))
        // 垂直滚动
        bannerDemo1.FillPageControlIndicatorRadius = 2;
        bannerDemo1.customPageControlIndicatorPadding = 10;
        bannerDemo1.customPageControlTintColor = UIColor.red;
        bannerDemo1.customPageControlInActiveTintColor = UIColor.white;
        bannerDemo1.customPageControlStyle = .snake

        scrollView.addSubview(bannerDemo1)

        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + .seconds(2)) {
            bannerDemo1.imagePaths = imagesURLStrings
        }

**Comment by LvJianfeng** [comment]
@wish-pig  
的确没加😂😂😂，后续更新考虑增加。

Thanks for your support.

**Comment by wish-pig** [comment]
还有一个问题，在这个style下，最后一个banner，不能左滑

**Comment by LvJianfeng** [comment]
@wish-pig  感谢支持，最近太忙没能及时更新，新版本1.4.8已更新
