### ISSUE TITLE
当没有设置imagePaths的时候滑动会数组越界

### ISSUE THREAD

**Issue by LinXunFeng** [LvJianfeng/LLCycleScrollView#33]
SKPhotoBrowser.swift

public convenience init(photos: [SKPhotoProtocol], initialPageIndex: Int) {
    self.init(nibName: nil, bundle: nil)
    *********************
    // photos.count = 0    
    // currentPageIndex = -1
    self.currentPageIndex = min(initialPageIndex, photos.count - 1)
    *********************
    // 崩溃
    animator.senderViewForAnimation = photos[currentPageIndex] as? UIView
}

当没有设置imagePaths的时候滑动会出现

**Comment by LvJianfeng** [comment]
@LinXunFeng  你是不是弄错地方了，这不是SKPhotoBrowser的仓库哈 😂😂

**Comment by LvJianfeng** [comment]
@LinXunFeng  如果你用到了
```swift
       // Demo--延时加载数据
        let bannerDemo1 = LLCycleScrollView.llCycleScrollViewWithFrame(CGRect.init(x: 0, y: 0, width: w, height: 200))
        scrollView.addSubview(bannerDemo1)
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + .seconds(2)) {
            bannerDemo1.imagePaths = imagesURLStrings
        }
```

没有数据就不用给imagePaths数据，默认是空数据不是nil

**Comment by LinXunFeng** [comment]
这个崩溃搞错了，不好意思，哈哈。
还有就是那个没有设置 imagePaths 的时候是否是可以设置为不可点击？

**Comment by LvJianfeng** [comment]
@LinXunFeng  应该不会出现崩溃呀，这个我后面控制下点击逻辑哈
如果急用，你可以先控制点击回调里，如果
```swift
imagePaths.count == 0 && index == 0 { return }
```
具体看你实现的是block回调还是协议回调

**Comment by LinXunFeng** [comment]
好的，十分感谢
