### ISSUE TITLE
swift 4.1 报错 No such module 'Kingfisher'

### ISSUE THREAD

**Issue by iOSCoderJane** [LvJianfeng/LLCycleScrollView#38]
platform :ios, '9.0'
install! 'cocoapods', :integrate_targets => false
target "TestCycleView do
pod 'LLCycleScrollView' 
end

报错信息：No such module 'Kingfisher'

**Comment by LvJianfeng** [comment]
@iOSCoderJane  为什么要设置这个integrate_targets，我没用过这个，你可以看看在pod install的时候Kingfisher有没有intall？
