### ISSUE TITLE
通过下拉刷新 重新赋值 imagePaths 会导致 LLCycleScrollView customPageControl 显示异常

### ISSUE THREAD

**Issue by GrsisFee** [LvJianfeng/LLCycleScrollView#45]
private func initViews() {
        // LLCycleScrollView 初始化代码
        csvMain.autoScroll = true
        csvMain.autoScrollTimeInterval = 5.0
        csvMain.imageViewContentMode = .scaleToFill
        csvMain.infiniteLoop = true
        csvMain.placeHolderImage = UIImage(named: "place_holder_image")
        csvMain.coverImage = UIImage(named: "place_holder_image")
        csvMain.backgroundColor = UIColor(hexString: ColorRes.transparent)
        csvMain.delegate = self
        
        csvMain.customPageControlStyle = .fill
        csvMain.pageControlBottom = 14.0
        csvMain.FillPageControlIndicatorRadius = 3.6
        csvMain.pageControlLeadingOrTrialingContact = 3
    }
    
// 下拉刷新 调用该方法，重置 LLCycleScrollView imagePaths
    private func reloadData() {
        var imagePaths: [String] = []
        for i in 0 ..< bannerData.count {
            let baseUrl = bannerData[i]["baseUrl"].stringValue
            let imageUrl = bannerData[i]["imageUrl"].stringValue
            
            imagePaths.append(baseUrl + imageUrl)
        }
        
        csvMain.imagePaths = imagePaths
// 重置 LLCycleScrollView imagePaths, 后 PageControl 显示错乱，但在一次autoScroll后  恢复正常。
    } 

请修复该问题。

**Comment by LvJianfeng** [comment]
@GrsisFee 我尝试了下，没有发生你说的问题额。
```swift
// Demo
let bannerDemo = LLCycleScrollView.llCycleScrollViewWithFrame(CGRect.init(x: 0, y:180, width: w, height: 200), imageURLPaths: ["s3.jpg","http://www.g-photography.net/file_picture/3/3587/4.jpg"], 
    print("当前点击图片的位置为:\(index)")
})
        
bannerDemo.autoScroll = true
bannerDemo.autoScrollTimeInterval = 5.0
bannerDemo.imageViewContentMode = .scaleToFill
bannerDemo.infiniteLoop = true
bannerDemo.delegate = self
        
bannerDemo.customPageControlTintColor = UIColor.red
bannerDemo.customPageControlStyle = .fill
bannerDemo.pageControlBottom = 14.0
bannerDemo.FillPageControlIndicatorRadius = 3.6
bannerDemo.pageControlLeadingOrTrialingContact = 3
        
scrollView.addSubview(bannerDemo)

DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + .seconds(10)) {
    bannerDemo.imagePaths = imagesURLStrings
}
```

请确认使用版本，最新版本存在的问题，可截图加DEMO代码哦

**Comment by GrsisFee** [comment]
我使用的版本 是 pod 1.5.0
根据我的经历 应该是：首次异步设置 bannerDemo.imagePaths 时不会出问题。下拉刷新后，第二次异步设置 bannerDemo.imagePaths 时。pageControl 显示错乱。

首次上传图片，不知道上传对了没。😶
@LvJianfeng 
![qq20180827-084057-hd](https://user-images.githubusercontent.com/17040266/44635221-3c52fd00-a9d5-11e8-826d-5239e18c5537.gif)

**Comment by GrsisFee** [comment]
同是中天人   这张图片 应该是在 第三张的位置。
@LvJianfeng

**Comment by LvJianfeng** [comment]
@GrsisFee  嗯，我就是按你说的方式跑的，没重现你的问题。
```swift

let imagesURLStrings = [
    "s3.jpg",
    "http://www.g-photography.net/file_picture/3/3587/4.jpg",
    "http://img2.zjolcdn.com/pic/0/13/66/56/13665652_914292.jpg",
    "http://c.hiphotos.baidu.com/image/w%3D400/sign=c2318ff84334970a4773112fa5c8d1c0/b7fd5266d0160924c1fae5ccd60735fae7cd340d.jpg",
    "http://img3.redocn.com/tupian/20150806/weimeisheyingtupian_4779232.jpg",
];


let imagesURLStrings2 = [
    "http://img3.redocn.com/tupian/20150806/weimeisheyingtupian_4779232.jpg",
    "http://c.hiphotos.baidu.com/image/w%3D400/sign=c2318ff84334970a4773112fa5c8d1c0/b7fd5266d0160924c1fae5ccd60735fae7cd340d.jpg",
    "http://img2.zjolcdn.com/pic/0/13/66/56/13665652_914292.jpg",
    "http://www.g-photography.net/file_picture/3/3587/4.jpg",
    "s3.jpg",
];

let titles2 = ["1",
              "2",
              "3",
              "4",
              "5"
];

let titles3 = ["1-5",
               "2-4",
               "3-3",
               "4-2",
               "5-1"
];


let bannerDemo = LLCycleScrollView.llCycleScrollViewWithFrame(CGRect.init(x: 0, y:180, width: w, height: 200), imageURLPaths: imagesURLStrings, titles: titles2, didSelectItemAtIndex: { index in
    print("当前点击图片的位置为:\(index)")
})
        
bannerDemo.autoScroll = true
bannerDemo.autoScrollTimeInterval = 1.0
bannerDemo.imageViewContentMode = .scaleToFill
bannerDemo.infiniteLoop = true
bannerDemo.delegate = self
        
bannerDemo.customPageControlTintColor = UIColor.red
bannerDemo.customPageControlStyle = .fill
bannerDemo.pageControlBottom = 14.0
bannerDemo.FillPageControlIndicatorRadius = 3.6
bannerDemo.pageControlLeadingOrTrialingContact = 3
        
scrollView.addSubview(bannerDemo)

DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + .seconds(10)) {
    bannerDemo.imagePaths = imagesURLStrings2
    bannerDemo.titles = titles3
}
```

你可以把这个代码复制到Demo中的viewcontroller跑一下～😁

**Comment by GrsisFee** [comment]
对了  我用的 xib 的方式。这有影响么？

**Comment by GrsisFee** [comment]
感谢哈，我已经解决了。是在 tableView cell 重用时。会多次赋值 imagePaths， 赋值 imagePaths (我看源码 赋值 该属性时 会致使 pageController 重建)，所以 pageController 就显示错乱了

**Comment by LvJianfeng** [comment]
@GrsisFee 嗯嗯，好的吧。这种头，一般都是放在header里比较好～👀
