### ISSUE TITLE
xcode10显示Type 'CAShapeLayerFillRule' (aka 'NSString') has no member 'evenOdd'

### ISSUE THREAD

**Issue by NullWorld** [LvJianfeng/LLCycleScrollView#47]
xcode10显示Type 'CAShapeLayerFillRule' (aka 'NSString') has no member 'evenOdd' 
pod 不引用就没问题，引用了就出问题。
LLCycleScrollView 1.5.1

**Comment by RiversMaJianCheng** [comment]
我也显示这个
