### ISSUE TITLE
回调的titles必须有值吗?

### ISSUE THREAD

**Issue by Jayxiang** [LvJianfeng/LLCycleScrollView#5]
没有值崩溃了..     还有能不能加一个纯文字的上下滚动的.

**Comment by LvJianfeng** [comment]
@Jayxiang 你是不是初始化的时候titles = nil哦，不要给nil，没有数据直接不赋值就行，这个我后面修改下逻辑，纯文字有需要我可以迭代下版本

**Comment by Jayxiang** [comment]
嗯,好的.   还有回调只有一种方式吗?

**Comment by LvJianfeng** [comment]
是的，目前回调只返回图片的index呢。其他也没什么数据呢。

发自我的 iPhone

**Comment by Jayxiang** [comment]
不是,我是说直接用LLCycleScrollView.llCycleScrollViewWithFrame(CGRect.init(x: 0, y: bannerDemo.ll_y + 205, width: w, height: 200))这种方式没有用闭包  怎么获取index呢

**Comment by LvJianfeng** [comment]
你可以看看有没有开放闭包对象，如果开放了你可以直接实现的呢

发自我的 iPhone

**Comment by LvJianfeng** [comment]
我弄手机给你看了，你实现这个
lldidSelectItemAtIndex就行了
发自我的 iPhone

**Comment by LvJianfeng** [comment]
@Jayxiang  版本1.2.7，增加支持纯文本
