### ISSUE TITLE
can you update Kingfisher for Swift 4.2 ?

### ISSUE THREAD

**Issue by c941010623** [LvJianfeng/LLCycleScrollView#51]
new Kingfisher will sup swift 4.2
can you update this ?

**Comment by LvJianfeng** [comment]
现在就可以的～你遇到什么问题？

**Comment by c941010623** [comment]
我希望能修改 圖片內的文字框高度

**Comment by LvJianfeng** [comment]
如果是直接拖入LLCycleScrollView源码，可以直接修改cellHeight属性的

**Comment by AaronDai23** [comment]
在1.5.1版本中LLFilledPageControl 在xcode10下报错
![_0a3648bd-7f74-4293-b30a-d92a7957ecd6](https://user-images.githubusercontent.com/19986142/47603063-3d29fe80-da19-11e8-8e97-5be7f56c1e0a.png)

**Comment by LvJianfeng** [comment]
请选择4.2编译

发自我的火星发射器
