### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by wanqingrongruo** [LvJianfeng/LLCycleScrollView#53]
老铁可以整理一下代码风格吗? 加上 swiftlint gitignore???
fork 了一下,改不动了嘤嘤嘤

**Comment by LvJianfeng** [comment]
为什么要gitignore，如果需要使用pod只有用到源文件～

**Comment by wanqingrongruo** [comment]
@LvJianfeng 创建项目时就应该创建 gitignore, 为了避免多人协作过程中出现配置等等的冲突....你可以浏览一下优秀的库...不过也是个人选择问题, 这个跟 cocoapods 无关

**Comment by LvJianfeng** [comment]
嗯嗯，点赞，后续会提交上。
