### ISSUE TITLE
放在 tableview 的 headerView 里面不主动滚动

### ISSUE THREAD

**Issue by shen5214444887** [LvJianfeng/LLCycleScrollView#56]
self.cycleScrollView = LLCycleScrollView()
cycleScrollView.frame = CGRect(x: 0, y: 0, width: UIScreen.main.bounds.size.width, height: CGFloat(185 * GM_SCREENWIDTH / 375))
cycleScrollView.backgroundColor = UIColor.white
cycleScrollView.autoScrollTimeInterval = 1.0
cycleScrollView.pageControl?.isEnabled = false
cycleScrollView.pageControlPosition = .center
cycleScrollView.pageControlBottom = 13
cycleScrollView.customPageControlStyle = .system
cycleScrollView.pageControlLeadingOrTrialingContact = 20
cycleScrollView.pageControlCurrentPageColor = UIColor.gm_theme
cycleScrollView.pageControlTintColor = UIColor.white
cycleScrollView.imagePaths = imagePaths
self.tableView.tableHeaderView = cycleScrollView
而且当给 imagePaths 重新赋值的时候，下面的pageControl的位置会重新从第一个开始，但图片还会从之前的位置开始滚动。

**Comment by shen5214444887** [comment]
需要到其他页面，再这个页面的时候会滚动

**Comment by ldy694** [comment]
有同样的问题需要解决

**Comment by shen5214444887** [comment]
设置完图片之后设置 autoScroll 为 true
self.cycleScrollView.autoScroll = true

**Comment by ldy694** [comment]
> 设置完图片之后设置 autoScroll 为 true
> self.cycleScrollView.autoScroll = true

你好，用
cycleView.autoScroll = true
是可以解决第一次不滚动问题，但是更新数据时，pageControl位置不对的问题还是存在，我试过用cycleView.pageControl?.currentPage = 0
但是没有效果，希望能得到你的帮助，谢谢

**Comment by shen5214444887** [comment]
pageControl位置不对的问题我也没解决，
目前就是更新数据时，判断两个图片数组数据一样就不更新图片数据。毕竟图片数据不是经常更新，可以解决大部分情况。

**Comment by ldy694** [comment]
> pageControl位置不对的问题我也没解决，
> 目前就是更新数据时，判断两个图片数组数据一样就不更新图片数据。毕竟图片数据不是经常更新，可以解决大部分情况。

好的，谢谢

**Comment by LvJianfeng** [comment]
@shen5214444887 @ldy694 
已更新了啊。
版本1.5.2

**Comment by LvJianfeng** [comment]
@shen5214444887  初始化方式建议使用 Demo的初始化方式。
