### ISSUE TITLE
当view不是屏幕宽度的时候，pagecontrol的位置不正确。

### ISSUE THREAD

**Issue by masakapa** [LvJianfeng/LLCycleScrollView#58]

**Comment by yz--lmy** [comment]
当view不是屏幕宽度的时候，pagecontrol的位置不能居中

**Comment by LvJianfeng** [comment]
@yz--lmy hi，你如果直接拖的的源码的话，建议把```LLCycleScrollView.swift```文件，替换```UIScreen.main.bounds.width```->```collectionView.frame.width```
后续版本，我会进行修改。
