### ISSUE TITLE
字体颜色大小 背景可以修改吗

### ISSUE THREAD

**Issue by Jayxiang** [LvJianfeng/LLCycleScrollView#6]
纯文字的字体 颜色 背景 可以修改吗  我都试了 好像不能  能增加一下吗

**Comment by LvJianfeng** [comment]
嗯嗯，好的，之前没有考虑这块，回头我改好了通知你。感谢支持。

发自我的 iPhone

**Comment by LvJianfeng** [comment]
@Jayxiang  已开放，详细见Demo。谢谢支持。

**Comment by Jayxiang** [comment]
en ,好的感谢. 还有那个小点的位置能自己设置吗  距离下面太低了

**Comment by LvJianfeng** [comment]
@Jayxiang 新版本1.2.9，假期出去了的，更新晚了哦。
