### ISSUE TITLE
swift5更新了，不支持

### ISSUE THREAD

**Issue by TrendyFeng** [LvJianfeng/LLCycleScrollView#60]

**Comment by LvJianfeng** [comment]
@TrendyFeng 支持的哇。

**Comment by PreAnti** [comment]
Kingfisher的版本已经更新到5.3.1，现在依赖的版本<= 4.10.1，方便的话更新一下，不然我在引用的时候没办法引用最新的Kingfisher。

**Comment by LvJianfeng** [comment]
@PreAnti  Hi，由于Kingfisher的4.10.1以上版本已经不支持iOS8.0，甚至Kingfisher 5.3.1需要iOS版本在iOS10+，所以没有进行依赖版本的更新，如果你需要使用LLCycleScrollView，我建议把源码拖入你的工程，仅需要拖入Lib文件夹。

**Comment by wangleibingkong** [comment]
弱弱的问一下，现在的代理方法貌似没有可以判断是人工滑动轮播图还是系统自动滚动轮播图的吧
