### ISSUE TITLE
图片contentMode问题

### ISSUE THREAD

**Issue by AilsaYouCan** [LvJianfeng/LLCycleScrollView#68]
let cycleView = LLCycleScrollView.llCycleScrollViewWithFrame(self.bounds)
        cycleView.contentMode = .scaleToFill
设置了无效

**Comment by LvJianfeng** [comment]
@AilsaYouCan  你没有看Demo，属性```imageViewContentMode ```

**Comment by crazypoo** [comment]
@LvJianfeng 这个字段照样无效
