### ISSUE TITLE
xib  使用文字时，一开始会出现裂图到情况，或者空白很久文字才出来，麻烦看看

### ISSUE THREAD

**Issue by xiaoxem** [LvJianfeng/LLCycleScrollView#69]

**Comment by xiaoxem** [comment]
如题，麻烦看看

**Comment by LvJianfeng** [comment]
@xiaoxem  纯文本的一般不建议你走xib，应该没有公开```isOnlyTitle```
如果你使用的源码且修改了，在使用纯文本的时候建议设置```coverImage```为一个纯色或透明或你需要的背景图，不然会显示默认的占位图。

具体看Demo里的纯文本的设置属性
