### ISSUE TITLE
 the image on  iphone5 iphone6 

### ISSUE THREAD

**Issue by wensnj** [LvJianfeng/LLCycleScrollView#7]
![image](https://cloud.githubusercontent.com/assets/13253654/25799010/f6c935c8-3415-11e7-81e1-91b84dae8de2.png)

**Comment by LvJianfeng** [comment]
这个应该是模拟器问题的，建议真机是一下。

发自我的 iPhone

**Comment by wensnj** [comment]
都一样 7p没问题 其他的小尺寸的都有问题

**Comment by wensnj** [comment]
一样的  小尺寸都是有偏移的

**Comment by wensnj** [comment]
我跑的是demo viewcontroller  viewDidAppear里面50行开始我都注释掉了

**Comment by LvJianfeng** [comment]
嗯嗯，应该是demo里约束问题，你看的是sb的demo呢

发自我的 iPhone

**Comment by LvJianfeng** [comment]
@wensnj  你好，你的问题我刚看了下，在sb下是存在问题，目前已经修复，新版本1.3.0，感谢支持。
