### ISSUE TITLE
影响Interface Builder不呈现自定义@IBDesignable视图

### ISSUE THREAD

**Issue by ijunfly** [LvJianfeng/LLCycleScrollView#9]
file://......./HomeStoryboard.storyboard: error: IB Designables: Failed to render and update auto layout status for ELHomeViewController : dlopen(LLCycleScrollView.framework, 1): Library not loaded: @rpath/Kingfisher.framework/Kingfisher
  Referenced from: LLCycleScrollView.framework
  Reason: image not found

代码在模拟器上编译并正确运行。此问题仅影响Interface Builder不呈现自定义@IBDesignable视图。

**Comment by LvJianfeng** [comment]
#8 你可以看看。
